#config_version=5

hardware:
    platform: lisy 

switches:
    slam:
        number: 76
    outhole:
        number: 66
    reset:
        number: 56
    test:
        number: 00
    coin1:
        number: 01
        tags: coin
    coin2:
        number: 02
        tags: coin
    start:
        number: 03
        tags: start
    tilt:
        number: 04
    laneA:
        number: 10
        tags: lane, playfield_active 
    laneB:
        number: 11
        tags: lane, playfield_active 
    laneC:
        number: 13
        tags: lane, playfield_active 
    laneD:
        number: 14
        tags: lane, playfield_active 
    dropYellow1:
        number: 20
        tags: dropYellow
    dropYellow2:
        number: 21
        tags: dropYellow
    dropYellow3:
        number: 23
        tags: dropYellow
    dropYellow4:
        number: 24
        tags: dropYellow
    dropRed1:
        number: 30
        tags: dropRed, dropUpper
    dropWhite2:
        number: 70
        tags: dropWhite, dropUpper
    dropRed3:
        number: 31
        tags: dropRed, dropUpper
    dropWhite4:
        number: 71
        tags: dropWhite, dropUpper
    dropRed5:
        number: 60
        tags: dropRed, dropUpper
    dropWhite6:
        number: 74
        tags: dropWhite, dropUpper
    dropRed7:
        number: 61
        tags: dropRed, dropUpper
    spinner:
        number: 33
    special:
        number: 40
    eject:
        number: 41
    lowerPop:
        number: 43
        tags: pop
    leftEb:
        number: 44
    standup10:
        number: 50
    rightEb:
        number: 51
    upperPop:
        number: 53
        tags: pop
    dangerLane:
        number: 54
    advBonus:
        number: 63
    inlane:
        number: 64
    outlane:
        number: 73
    