#config_version=5

hardware:
    platform: lisy 

#lisy:
#    connection: network
#    network_port: 5963
#    network_host: localhost #192.168.80.1 #192.168.1.32
    
lisy:
  connection: network
  network_port: 5963
  network_host: "localhost"
  poll_hz: 100

switches:
    slam:
        number: 76
    outhole:
        number: 66
    reset:
        number: 56
    test:
        number: 00
    coin1:
        number: 01
        tags: coin
    coin2:
        number: 02
        tags: coin
    start:
        number: 03
        tags: start
    tilt:
        number: 04
    laneA:
        number: 10
        ignore_window_ms: 100ms
        tags: lane, playfield_active 
    laneB:
        number: 11
        ignore_window_ms: 100ms
        tags: lane, playfield_active 
    laneC:
        number: 13
        ignore_window_ms: 100ms
        tags: lane, playfield_active 
    laneD:
        number: 14
        ignore_window_ms: 100ms
        tags: lane, playfield_active 
    dropYellow1:
        number: 20
        tags: dropYellow
    dropYellow2:
        number: 21
        tags: dropYellow
    dropYellow3:
        number: 23
        tags: dropYellow
    dropYellow4:
        number: 24
        tags: dropYellow
    dropRed1:
        number: 30
        tags: dropRed, dropUpper
    dropWhite2:
        number: 70
        tags: dropWhite, dropUpper
    dropRed3:
        number: 31
        tags: dropRed, dropUpper
    dropWhite4:
        number: 71
        tags: dropWhite, dropUpper
    dropRed5:
        number: 60
        tags: dropRed, dropUpper
    dropWhite6:
        number: 74
        tags: dropWhite, dropUpper
    dropRed7:
        number: 61
        tags: dropRed, dropUpper
    spinner:
        number: 33
    special:
        number: 40
    eject:
        number: 41
    lowerPop:
        number: 43
        tags: pop
    leftEb:
        number: 44
    standup10:
        number: 50
    rightEb:
        number: 51
    upperPop:
        number: 53
        tags: pop
    dangerLane:
        number: 54
    advBonus:
        ignore_window_ms: 100ms
        number: 63
    inlane:
        number: 64
    outlane:
        number: 73

drop_targets:
    yellow1:
        switch: dropYellow1
        reset_coil: yellowReset
    yellow2:
        switch: dropYellow2
        reset_coil: yellowReset
    yellow3:
        switch: dropYellow3
        reset_coil: yellowReset
    yellow4:
        switch: dropYellow4
        reset_coil: yellowReset
    red1:
        switch: dropRed1
        reset_coil: upperReset
    white2:
        switch: dropWhite2
        reset_coil: upperReset
    red3:
        switch: dropRed3
        reset_coil: upperReset
    white4:
        switch: dropWhite4
        reset_coil: upperReset
    red5:
        switch: dropRed5
        reset_coil: upperReset
    white6:
        switch: dropWhite6
        reset_coil: upperReset
    red7:
        switch: dropRed7
        reset_coil: upperReset

drop_target_banks:
    yellow:
        drop_targets: yellow1, yellow2, yellow3, yellow4
        reset_coils: yellowReset
        ignore_switch_ms: 1000ms
        reset_on_complete: 500ms
        reset_events: 
            drop_target_bank_yellow_down
            ball_starting
            machine_reset_phase_3
    red:
        drop_targets: red1, red3, red5, red7
        reset_coils: upperReset
        ignore_switch_ms: 1000ms
        reset_on_complete: 500ms
        reset_events: 
            drop_target_bank_red_down{devices.drop_target_banks.white.complete==false}
            ball_starting
            machine_reset_phase_3
    white:
        drop_targets: white2, white4, white6
        reset_coils: upperReset
        ignore_switch_ms: 1000ms
        reset_on_complete: 500ms
        reset_events: 
            drop_target_bank_white_down{devices.drop_target_banks.red.complete==false}


    
coils:
    outhole:
        number: 1
    knocker:
        number: 2
    tens:
        number: 3
    hundreds:
        number: 4
    thousands:
        number: 5
    eject:
        number: 6
    yellowReset:
        number: 7
        default_pulse_ms: 50ms
    upperReset:
        number: 8
        default_pulse_ms: 50ms

digital_outputs:
    game_over_relay:
        number: 1
        type: light
        enable_events: ball_started
        disable_events: game_will_end, machine_reset_phase_3
    tilt_relay:
        number: 2
        type: light
        enable_events: tilt_started
        disable_events: tiltl_will_end

lights:
    highScore:
        number: 3
    shootAgain:
        number: 4
    spinner:
        number: 5
    advMultiplier:
        number: 6
    lowerLaneD:
        number: 7
        tags: lane, laneD
    lowerLaneC:
        number: 8
        tags: lane, laneC
    lowerLaneA:
        number: 9
        tags: lane, laneA
    lowerLaneB:
        number: 10
        tags: lane, laneB
    leftEb:
        number: 11
    whiteDrops:
        number: 12
    upperLaneD:
        number: 14
        tags: lane, laneD
    upperLaneC:
        number: 13
        tags: lane, laneC
    upperLaneA:
        number: 16
        tags: lane, laneA
    upperLaneB:
        number: 15
        tags: lane, laneB
    special:
        number: 17
    collectBonus:
        number: 18
    bonus5x:
        number: 19
        tags: bonusMult
    bonus4x:
        number: 20
        tags: bonusMult
    bonus2x:
        number: 21
        tags: bonusMult
    bonus3x:
        number: 22
        tags: bonusMult
    bonus1k:
        number: 23
        tags: bonus
    bonus2k:
        number: 24
        tags: bonus
    bonus3k:
        number: 25
        tags: bonus
    bonus4k:
        number: 26
        tags: bonus
    bonus5k:
        number: 27
        tags: bonus
    bonus6k:
        number: 28
        tags: bonus
    bonus7k:
        number: 29
        tags: bonus
    bonus8k:
        number: 30
        tags: bonus
    bonus9k:
        number: 31
        tags: bonus
    bonus10k:
        number: 32
        tags: bonus
    bonus20k:
        number: 33
        tags: bonus
    rightEb:
        number: 36

segment_displays:
  display5:
    number: 0
  display1:
    number: 1
  display2:
    number: 2
  display3:
    number: 3
  display4:
    number: 4
segment_display_player:
  # empty all displays on game start and setup display5
  game_start:
    display1:
      text: ""
    display2:
      text: ""
    display3:
      text: ""
    display4:
      text: ""
    display5:
      text: "{current_player.ball:d}"

  # clear only display5 after game
  game_ended{machine.player1_score > 0}:
    display1:
      text: "{machine.player1_score:d}"
  game_ended{machine.player2_score > 0}:
    display2:
      text: "{machine.player2_score:d}"
  game_ended{machine.player3_score > 0}:
    display3:
      text: "{machine.player3_score:d}"
  game_ended{machine.player4_score > 0}:
    display4:
      text: "{machine.player4_score:d}"
  game_ended:
    display5:
      text: ""

  # flash display on player turn
  #player_turn_started.1{number==1}:
  #  display1:
  #    action: flash
  player_turn_ended.2{number==1}:
    display1:
      action: no_flash
  #player_turn_started.3{number==2}:
  #  display2:
  #    action: flash
  player_turn_ended.4{number==2}:
    display2:
      action: no_flash
  #player_turn_started.5{number==3}:
  #  display3:
  #    action: flash
  player_turn_ended.6{number==3}:
    display3:
      action: no_flash
  #player_turn_started.7{number==4}:
  #  display4:
  #    action: flash
  player_turn_ended.8{number==4}:
    display4:
      action: no_flash

  # show score when adding players
  player_added.1{num==1}:
    display1:
      text: "{players[0].score:d}"
  player_added.2{num==2}:
    display2:
      text: "{players[1].score:d}"
  player_added.3{num==3}:
    display3:
      text: "{players[2].score:d}"
  player_added.4{num==4}:
    display4:
      text: "{players[3].score:d}"

ball_devices:
    bd_outhole:
        ball_switches: outhole
        eject_coil: outhole
        eject_targets: playfield
        tags: drain, home, trough
    bd_eject:
        ball_switches: eject
        eject_coil: eject

ball_holds:
    eject:
        hold_devices: bd_eject
        release_one_events: 
          - bonusDone
          - ejectBall
        #enable_events: player_scoreBonus{value==1}
        #disable_events: 
        #  - player_scoreBonus{value==0}
        #  - ball_started



playfields:
    playfield:
        default_source_device: bd_outhole
        tags: default

virtual_platform_start_active_switches:
    outhole

modes:
  - base
  - tilt
  - attract

player_vars:
    spinner:
        initial_value: 0
    a:
        initial_value: 1
    b:
        initial_value: 1
    c:
        initial_value: 1
    d:
        initial_value: 1
    superSpinner:
        initial_value: 0
    redDown:
        initial_value: 0
    whiteDown:
        initial_value: 0
    advX:
        initial_value: 1
    scoreBonus:
        initial_value: 0
    bonus:
        initial_value: 1
    whiteDrops:
        initial_value: 0
    bonus_multiplier:
        initial_value: 1
    heldBonus:
        initial_value: 0
    heldBonusX:
        initial_value: 0
    special:
        initial_value: 0
    leftEb:
        initial_value: 0
    rightEb:
        initial_value: 0
    collecting:
        initial_value: 0
    thousands:
        initial_value: 0
    hundreds:
        initial_value: 0
    tens: 
        initial_value: 0

shows:
    flashing:
      - time: 0
        lights:
            (lights): on
      - time: .5
        lights:
            (lights): off
      - time: 1
    knock:
      - time: 0
        coils: knocker
      - time: 200ms

ball_saves:
    default:
        active_time: 10s
        enable_events: ball_started
        timer_start_events: sw_lane_active, upperPop_active

hardware_sound_systems:
   default:
      label: LISY