#config_version=5

hardware:
    platform: lisy 

switches:
    slam:
        number: 76
    outhole:
        number: 66
    reset:
        number: 56
    test:
        number: 00
    coin1:
        number: 01
        tags: coin
    coin2:
        number: 02
        tags: coin
    start:
        number: 03
        tags: start
    tilt:
        number: 04
    laneA:
        number: 10
        tags: lane, playfield_active 
    laneB:
        number: 11
        tags: lane, playfield_active 
    laneC:
        number: 13
        tags: lane, playfield_active 
    laneD:
        number: 14
        tags: lane, playfield_active 
    dropYellow1:
        number: 20
        tags: dropYellow
    dropYellow2:
        number: 21
        tags: dropYellow
    dropYellow3:
        number: 23
        tags: dropYellow
    dropYellow4:
        number: 24
        tags: dropYellow
    dropRed1:
        number: 30
        tags: dropRed, dropUpper
    dropWhite2:
        number: 70
        tags: dropWhite, dropUpper
    dropRed3:
        number: 31
        tags: dropRed, dropUpper
    dropWhite4:
        number: 71
        tags: dropWhite, dropUpper
    dropRed5:
        number: 60
        tags: dropRed, dropUpper
    dropWhite6:
        number: 74
        tags: dropWhite, dropUpper
    dropRed7:
        number: 61
        tags: dropRed, dropUpper
    spinner:
        number: 33
    special:
        number: 40
    eject:
        number: 41
    lowerPop:
        number: 43
        tags: pop
    leftEb:
        number: 44
    standup10:
        number: 50
    rightEb:
        number: 51
    upperPop:
        number: 53
        tags: pop
    dangerLane:
        number: 54
    advBonus:
        number: 63
    inlane:
        number: 64
    outlane:
        number: 73

drop_targets:
    yellow1:
        switch: dropYellow1
        reset_coil: yellowReset
    yellow2:
        switch: dropYellow2
        reset_coil: yellowReset
    yellow3:
        switch: dropYellow3
        reset_coil: yellowReset
    yellow4:
        switch: dropYellow4
        reset_coil: yellowReset
    red1:
        switch: dropRed1
        reset_coil: upperReset
    white2:
        switch: dropWhite2
        reset_coil: upperReset
    red3:
        switch: dropRed3
        reset_coil: upperReset
    white4:
        switch: dropWhite4
        reset_coil: upperReset
    red5:
        switch: dropRed5
        reset_coil: upperReset
    white6:
        switch: dropWhite6
        reset_coil: upperReset
    red7:
        switch: dropRed7
        reset_coil: upperReset

drop_target_banks:
    yellow:
        drop_targets: yellow1, yellow2, yellow3, yellow4
        reset_coils: yellowReset
        reset_on_complete: 500ms
    upper:
        drop_targets: red1, white2, red3, white4, red5, white6, red7
        reset_coils: upperReset
        reset_on_complete: 500ms


    
coils:
    outhole:
        number: 1
    knocker:
        number: 2
    tens:
        number: 3
    hundreds:
        number: 4
    thousands:
        number: 5
    eject:
        number: 6
    yellowReset:
        number: 7
    upperReset:
        number: 8

digital_outputs:
    game_over_relay:
        number: 1
        type: light
        enable_events: ball_started
        disable_events: ball_will_end
    tilt_relay:
        number: 2
        type: light

lights:
    highScore:
        number: 3
    shootAgain:
        number: 4
    spinner:
        number: 5
    advMultiplier:
        number: 6
    lowerLaneD:
        number: 7
        tags: lane, laneD
    lowerLaneC:
        number: 8
        tags: lane, laneC
    lowerLaneA:
        number: 9
        tags: lane, laneA
    lowerLaneB:
        number: 10
        tags: lane, laneB
    leftEb:
        number: 11
    whiteDrops:
        number: 12
    upperLaneD:
        number: 14
        tags: lane, laneD
    upperLaneC:
        number: 13
        tags: lane, laneC
    upperLaneA:
        number: 16
        tags: lane, laneA
    upperLaneB:
        number: 15
        tags: lane, laneB
    special:
        number: 17
    collectBonus:
        number: 18
    bonus5x:
        number: 19
        tags: bonusMult
    bonus4x:
        number: 20
        tags: bonusMult
    bonus2x:
        number: 21
        tags: bonusMult
    bonus3x:
        number: 22
        tags: bonusMult
    bonus1k:
        number: 23
        tags: bonus
    bonus2k:
        number: 24
        tags: bonus
    bonus3k:
        number: 25
        tags: bonus
    bonus4k:
        number: 26
        tags: bonus
    bonus5k:
        number: 27
        tags: bonus
    bonus6k:
        number: 28
        tags: bonus
    bonus7k:
        number: 29
        tags: bonus
    bonus8k:
        number: 30
        tags: bonus
    bonus9k:
        number: 31
        tags: bonus
    bonus10k:
        number: 32
        tags: bonus
    bonus20k:
        number: 33
        tags: bonus
    rightEb:
        number: 36

segment_displays:
  dispInfo:
    number: 0
  disp1:
    number: 1
  disp2:
    number: 2
  disp3:
    number: 3
  disp4:
    number: 4

ball_devices:
    bd_outhole:
        ball_switches: outhole
        eject_coil: outhole
        eject_targets: playfield
        tags: drain, home, trough
    bd_eject:
        ball_switches: eject
        eject_coil: eject

ball_holds:
    eject:
        hold_devices: bd_eject



playfields:
    playfield:
        default_source_device: bd_outhole
        tags: default

virtual_platform_start_active_switches:
    outhole